### ISSUE TITLE
Inconsistent handling of null and empty objects on serialization/deserialization

### ISSUE THREAD

**Issue by robertbcalhoun** [JKISoftware/JKI-JSON-Serialization#9] opened 2016-08-25 03:14 UTC
Hi Tomi,

Thanks for your work on this great library! I've been working with Amazon's AWS service and needed a way to manipulate AWS-generated JSON containing run-time defined objects. I was looking at building something from scratch just when the JKI JSON library was released, and modifying that was a much better solution. I've pushed some code to github and generated a pull request for you. (Note my code is LV2015, let me know if I need to back-port to 2013.)

While working on this I found an inconsistency in how the library handles default (void) variants. These map to "null" on serialization, but on deserialization JSON "null" maps to a default variant cast to a variant while JSON empty object "{}" maps to a default (void) variant. The result is failure of a round trip test of default variant moving from LabVIEW -> JSON string ->  LabVIEW. 

My code use variant attributes to represent JSON objects, so I find the latter use (default variant is an empty object) more consistent. (An empty object has zero attributes, and object with one name/value pair has one attribute, etc.) But then something else is needed to generate null from LabVIEW. The variant-cast-to-variant returned the deserialization library is a little weird, but it would work.

-Rob Calhoun

**Comment by tmaila** [comment] 2016-08-25 04:54
Rob,

Thanks for your feedback. You're right the there's an inconsistency that should be fixed. Void variant should actually generate an error when being serialized and only empty variant should serialize to a null JSON object (or {}). To properly serialize an empty variant, you need apply "to variant" to convert a void variant to an empty variant. This is because variants don't automatically get this treatment unlike all other types in LabVIEW when wired to a variant input terminal. It's a bit confusing but that's how LabVIEW was designed. I left the inconsistency to the Library because I thought that this would be more intuitive but I am not sure if it actually causing more confusion.

Empty variant is a value and similar in behavior to JSON null or {}. Void variant is not a LabVIEW value but lack of value and it does not behave like a value and hence cannot be used by the JSON library in deserialization. For example you cannot assign a label to a void variant and hence you cannot deserialize { "A" : { } } into a cluster with a void variant labeled "A". 

I will look into the inconsistency between {} and null as they should behave the same and both map into an empty variant.

**Comment by tmaila** [comment] 2016-08-25 05:37
@robertbcalhoun, I was unable to reproduce the inconsistency. Void variant (incorrectly) maps to JSON null but as I said I left this for convenience. Wrapped void variant correctly maps to null on serialization. On deserialization I get both null and {} to deserialize to a wrapped empty variant as I would expect. I also tested deserializing {"A":{}} and {"A":null} and they both deserialized to a cluster with an empty variant.

Can you upload code that demonstrates the incorrect behavior?

**Comment by tmaila** [comment] 2016-08-31 21:49
Fixed in 1.0.5 by removing support for void type.

**Closed as completed by tmaila** 2016-08-31 21:49 UTC
